spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/flow_engine}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

server:
  port: ${SERVER_PORT:8060}
