spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

server:
  port: ${PORT:8060}


app:
  encryption:
    secret: ${ENCRYPTION_SECRET:12345678901234567890123456789012}



llm:
  provider: ${LLM_PROVIDER:ollama}

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  model: ${OLLAMA_MODEL:llama3.2}

groq:
  api:
    key: ${GROQ_API_KEY:}
  model: ${GROQ_MODEL:llama-3.1-8b-instant}


  logging:
    level:
      com.example.flowengine.service.AssertionGeneratorService: DEBUG